SELECT DISTINCT 
    me.CD_MARCA, 
    me.NM_MARCA, 
    a.CD_ASSOCIADO, 
    FU_HASH_LOGIN_DECRIPTA(u.USER_PASSWORD) as PASSWORD,
    a.NM_ASSOCIADO, 
    a.ID_INATIVO, 
    a.NR_CPF, 
    a.DT_NASCIMENTO,
    a.DS_EMAIL
FROM ADMPROD.TBOD_EMPRESA e
    INNER JOIN ADMPROD.TBOD_ASSOCIADO a
    ON a.CD_EMPRESA = e.CD_EMPRESA
    INNER JOIN ADMPROD.TBOD_MARCA_EMPRESA me
    ON e.CD_MARCA = me.CD_MARCA
    LEFT JOIN TBOD_USER u
    ON a.CD_ASSOCIADO = u.USER_LOGIN
WHERE
    a.ID_INATIVO = 'N'
    AND a.CD_ASSOCIADO = ?
    AND me.CD_MARCA = ?
    AND u.USER_PASSWORD IS NOT null
    AND a.NR_CPF IS NOT null
    AND a.DS_EMAIL IS NOT null
    AND ROWNUM < 10
GROUP BY 
    me.CD_MARCA, 
    me.NM_MARCA, 
    a.CD_ASSOCIADO, 
    a.NM_ASSOCIADO, 
    u.USER_PASSWORD, 
    a.ID_INATIVO, 
    a.NR_CPF, 
    a.DT_NASCIMENTO,
    a.DS_EMAIL
ORDER BY
    DBMS_RANDOM.VALUE